language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
install:
  - python setup.py install
  - pip install pytest pytest-coverage flake8
script:
  - pytest tests/
  - flake8 src/